INSERT INTO commune (id_commune,name_commune,id_province)VALUES (29,'y',154);
INSERT INTO commune (id_commune,name_commune,id_province)VALUES (141,'el',86);
INSERT INTO commune (id_commune,name_commune,id_province)VALUES (160,'no',16);
INSERT INTO commune (id_commune,name_commune,id_province)VALUES (91,'aquella',186);
INSERT INTO commune (id_commune,name_commune,id_province)VALUES (189,'nos',61);
INSERT INTO commune (id_commune,name_commune,id_province)VALUES (153,'mas',35);
INSERT INTO commune (id_commune,name_commune,id_province)VALUES (37,'suceden',125);
INSERT INTO commune (id_commune,name_commune,id_province)VALUES (192,'que',191);
INSERT INTO commune (id_commune,name_commune,id_province)VALUES (111,'mi',163);
INSERT INTO commune (id_commune,name_commune,id_province)VALUES (32,'y',24)