INSERT INTO donation_campaign (id_donation_campaign,goal,actual_amount,anonymous_donation)VALUES (29,90,154,141);
INSERT INTO donation_campaign (id_donation_campaign,goal,actual_amount,anonymous_donation)VALUES (146,86,160,106);
INSERT INTO donation_campaign (id_donation_campaign,goal,actual_amount,anonymous_donation)VALUES (16,91,9,186);
INSERT INTO donation_campaign (id_donation_campaign,goal,actual_amount,anonymous_donation)VALUES (189,67,61,153);
INSERT INTO donation_campaign (id_donation_campaign,goal,actual_amount,anonymous_donation)VALUES (40,35,37,69);
INSERT INTO donation_campaign (id_donation_campaign,goal,actual_amount,anonymous_donation)VALUES (125,192,42,191);
INSERT INTO donation_campaign (id_donation_campaign,goal,actual_amount,anonymous_donation)VALUES (111,180,163,32);
INSERT INTO donation_campaign (id_donation_campaign,goal,actual_amount,anonymous_donation)VALUES (129,24,1,79);
INSERT INTO donation_campaign (id_donation_campaign,goal,actual_amount,anonymous_donation)VALUES (154,113,38,168);
INSERT INTO donation_campaign (id_donation_campaign,goal,actual_amount,anonymous_donation)VALUES (182,47,89,127)