INSERT INTO donation (id_donation,id_user,total_amount,ong,campaign,id_action)VALUES (29,90,154,'habiendo','el',86);
INSERT INTO donation (id_donation,id_user,total_amount,ong,campaign,id_action)VALUES (160,106,16,'y','aquella',186);
INSERT INTO donation (id_donation,id_user,total_amount,ong,campaign,id_action)VALUES (189,67,61,'bien','mas',35);
INSERT INTO donation (id_donation,id_user,total_amount,ong,campaign,id_action)VALUES (37,69,125,'no','que',191);
INSERT INTO donation (id_donation,id_user,total_amount,ong,campaign,id_action)VALUES (111,180,163,'no','y',24);
INSERT INTO donation (id_donation,id_user,total_amount,ong,campaign,id_action)VALUES (1,79,154,'que','hombre',168);
INSERT INTO donation (id_donation,id_user,total_amount,ong,campaign,id_action)VALUES (182,47,89,'durables,','mi',25);
INSERT INTO donation (id_donation,id_user,total_amount,ong,campaign,id_action)VALUES (110,193,121,'durado','esta',101);
INSERT INTO donation (id_donation,id_user,total_amount,ong,campaign,id_action)VALUES (57,118,105,'suceden','por',72);
INSERT INTO donation (id_donation,id_user,total_amount,ong,campaign,id_action)VALUES (96,152,162,'a','de',50)