INSERT INTO gathering_center (id_gathering_center,status_gathering_center,description_gathering_center)VALUES (29,90,'esta');
INSERT INTO gathering_center (id_gathering_center,status_gathering_center,description_gathering_center)VALUES (141,146,'el');
INSERT INTO gathering_center (id_gathering_center,status_gathering_center,description_gathering_center)VALUES (160,106,'de');
INSERT INTO gathering_center (id_gathering_center,status_gathering_center,description_gathering_center)VALUES (91,9,'pues');
INSERT INTO gathering_center (id_gathering_center,status_gathering_center,description_gathering_center)VALUES (189,67,'estas');
INSERT INTO gathering_center (id_gathering_center,status_gathering_center,description_gathering_center)VALUES (153,40,'es');
INSERT INTO gathering_center (id_gathering_center,status_gathering_center,description_gathering_center)VALUES (37,69,'sean');
INSERT INTO gathering_center (id_gathering_center,status_gathering_center,description_gathering_center)VALUES (192,42,'ti');
INSERT INTO gathering_center (id_gathering_center,status_gathering_center,description_gathering_center)VALUES (111,180,'que,');
INSERT INTO gathering_center (id_gathering_center,status_gathering_center,description_gathering_center)VALUES (32,129,'dijo:')