INSERT INTO user (id_user,name,password,type,email,active,id_user_record,id_rnv)VALUES (29,'y','esta','habiendo','el',True,160,106);
INSERT INTO user (id_user,name,password,type,email,active,id_user_record,id_rnv)VALUES (16,'y','aquella','pues','a',True,61,153);
INSERT INTO user (id_user,name,password,type,email,active,id_user_record,id_rnv)VALUES (40,'es','un','suceden','sean',True,42,191);
INSERT INTO user (id_user,name,password,type,email,active,id_user_record,id_rnv)VALUES (111,'mi','que,','no','y',True,1,79);
INSERT INTO user (id_user,name,password,type,email,active,id_user_record,id_rnv)VALUES (154,'que','hombre','congojarte','me',True,89,127);
INSERT INTO user (id_user,name,password,type,email,active,id_user_record,id_rnv)VALUES (180,'dijo:','posible','no','el',True,154,101);
INSERT INTO user (id_user,name,password,type,email,active,id_user_record,id_rnv)VALUES (57,'ni','porque','suceden','por',True,96,152);
INSERT INTO user (id_user,name,password,type,email,active,id_user_record,id_rnv)VALUES (162,'a','de','hace','congojarte',True,142,153);
INSERT INTO user (id_user,name,password,type,email,active,id_user_record,id_rnv)VALUES (102,'bien','mal','Sancho,','se',True,32,150);
INSERT INTO user (id_user,name,password,type,email,active,id_user_record,id_rnv)VALUES (141,'dijo:','manera,','ni','que',True,124,130)